// @ts-nocheck
import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'Space Grotesk', 'Satoshi', 'sans-serif'],
        heading: ['Space Grotesk', 'Inter', 'sans-serif'],
        montserrat: ["Montserrat", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        socilume: {
          darkBg: "#1F1F1F",
          darkAlt: "#111111",
          pureBlack: "#000000",
          titaniumLight: "#6B6B6B",
          titaniumDark: "#2D2D2D",
          textWhite: "#F5F5F7",
          textGray: "#A0A0A0",
          silver: "#B0B0B0",
          lightGray: "#E6E6E6",
          cardBg: "#2F2F2F",
          pricingBg: "#3A3A3A",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        navy: {
          DEFAULT: "#1E1E28",
          50: "#F4F4F6",
          100: "#EAEAF0",
          200: "#D3D4DD",
          300: "#BDBFCB",
          400: "#9FA1B3",
          500: "#7F8195",
          600: "#5E5F6D",
          700: "#3F3F49",
          800: "#1E1E28",
          900: "#111118",
        },
        gold: {
          DEFAULT: "#D8CBAF",
          50: "#FBFAF7",
          100: "#F5F1E5",
          200: "#E5DCC0",
          300: "#D8CBAF",
          400: "#C1B58E",
          500: "#AA9F6F",
          600: "#958A59",
          700: "#786E46",
          800: "#5D5436",
          900: "#3F3A25",
        },
        coral: {
          DEFAULT: "#FF9681",
          50: "#FFF3F0",
          100: "#FFE4DE",
          200: "#FFC8BE",
          300: "#FFAAA0",
          400: "#FF9681",
          500: "#FF7C65",
          600: "#E96651",
          700: "#C94D3C",
          800: "#A03A2B",
          900: "#73271C",
        },
        azure: {
          DEFAULT: "#A7C7DD",
          50: "#F5F9FC",
          100: "#EAF2F9",
          200: "#D5E5F2",
          300: "#BED8EC",
          400: "#A7C7DD",
          500: "#86B2D1",
          600: "#649CBD",
          700: "#45779B",
          800: "#2F5169",
          900: "#1C3240",
        },
        cosmic: {
          deep: "#1C1C24",
          starlight: "#757280",
          nebula: "#F295AF",
          aurora: "#C5FFF8",
          white: "#FFFFFF",
        },
        success: {
          DEFAULT: "#C5FFF8",
          foreground: "#1C1C24",
        },
        dreamflow: {
          background: '#0A0A23',
          surface: '#18182F',
          primary: '#7B61FF',
          secondary: '#00FFD0',
          highlight: '#FF61D2',
          text: '#FFFFFF',
          textMuted: '#B0B3C6',
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        hang: {
          "0%, 100%": { transform: "rotate(-1deg)" },
          "50%": { transform: "rotate(1deg)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeInLeft: {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        fadeInRight: {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 8px rgba(255, 255, 255, 0.15)" },
          "50%": { boxShadow: "0 0 12px rgba(255, 255, 255, 0.25)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        float: "float 3s ease-in-out infinite",
        hang: "hang 3s ease-in-out infinite",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-in-left": "fadeInLeft 0.7s ease-out forwards",
        "fade-in-right": "fadeInRight 0.7s ease-out forwards",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
      },
      backgroundImage: {
        "cosmic-gradient": "linear-gradient(135deg, #1C1C24 0%, #757280 100%)",
        'dreamflow-gradient': 'linear-gradient(90deg, #7B61FF 0%, #00FFD0 100%)',
        "titanium-gradient": "linear-gradient(135deg, #2D2D2D 30%, #6B6B6B 90%)",
        "titanium-gradient-hover": "linear-gradient(135deg, #3D3D3D 30%, #7B7B7B 90%)",
      },
      boxShadow: {
        "titanium": "0 4px 12px rgba(0, 0, 0, 0.6), inset 0 0 8px rgba(255, 255, 255, 0.15)",
        "titanium-hover": "0 4px 12px rgba(0, 0, 0, 0.6), inset 0 0 8px rgba(255, 255, 255, 0.15), 0 0 12px rgba(255, 255, 255, 0.2)",
        "card": "0 6px 15px rgba(0, 0, 0, 0.7), inset 0 0 10px rgba(255, 255, 255, 0.15)",
        "pricing": "0 8px 20px rgba(0, 0, 0, 0.6), inset 0 0 10px rgba(255, 255, 255, 0.15)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
